--
-- Custom Domains Database Schema
--
-- This SQL schema defines the 'custom_domains' table, which is essential for managing
-- custom domain functionality in a multi-tenant SaaS application. It tracks each
-- tenant's custom domain, its verification status, and relevant configuration details.
--
-- Table: custom_domains
-- Description: Stores information about custom domains configured by tenants.
--

CREATE TABLE custom_domains (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- Unique identifier for the custom domain entry
    tenant_id UUID NOT NULL,                        -- Foreign key linking to the tenants table (assuming a 'tenants' table exists)
                                                    -- This establishes ownership of the custom domain by a specific tenant.

    domain_name VARCHAR(255) NOT NULL UNIQUE,       -- The custom domain name provided by the tenant (e.g., app.customer.com).
                                                    -- Must be unique across all tenants.

    txt_record_value VARCHAR(255) NOT NULL,         -- A unique token generated by the system for TXT record verification.
                                                    -- This token is used to prove domain ownership.

    cname_target VARCHAR(255) NOT NULL,             -- The expected CNAME target that the custom domain should point to
                                                    -- (e.g., your-platform-subdomain.your-saas.com).
                                                    -- This is used for CNAME validation.

    verification_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
                                                    -- Current status of the domain verification process.
                                                    -- Possible values: 'PENDING', 'VERIFIED', 'FAILED', 'ERROR'.

    last_verified_at TIMESTAMP WITH TIME ZONE,      -- Timestamp of the last successful verification. Null if never verified.
    
    is_active BOOLEAN NOT NULL DEFAULT FALSE,       -- Flag to indicate if the custom domain is active and ready to serve traffic.
                                                    -- Only active and verified domains should be used in routing.

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), -- Timestamp when the record was created.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), -- Timestamp of the last update to the record.

    -- Add a foreign key constraint to the tenants table
    -- IMPORTANT: Replace 'tenants' with your actual tenant table name if it's different.
    -- Assuming 'tenants' table has an 'id' column of type UUID.
    -- Uncomment and adjust the following line if you have a 'tenants' table:
    -- CONSTRAINT fk_tenant
    --     FOREIGN KEY(tenant_id) 
    --     REFERENCES tenants(id)
    --     ON DELETE CASCADE,

    -- Ensure that a tenant cannot add the same domain twice.
    -- (Though 'domain_name' UNIQUE constraint already handles this for the domain itself)

    -- Add indexes for performance
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_domain_name (domain_name),
    INDEX idx_verification_status (verification_status),
    INDEX idx_is_active (is_active)
);

-- Optional: Add a trigger to automatically update the 'updated_at' column on record modification.
-- This example is for PostgreSQL. Adjust for other databases if necessary.
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_custom_domains_updated_at
BEFORE UPDATE ON custom_domains
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
