/home/getloopx/getloopx-core/crm-service/logs/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 getloopx getloopx
    sharedscripts
    postrotate
        pm2 reload all > /dev/null
    endscript
}
